/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ApostilbibleAnnotation from './annotation.defs.js'

const $nsid = 'com.apostilbible.highlight'

type $nsid = typeof $nsid

export { $nsid }

/** A color highlight on exactly one verse. Clients use a canonical verse-derived record key, so a repository has one highlight per verse. */
type Main = {
  $type: 'com.apostilbible.highlight'
  verse: ApostilbibleAnnotation.VerseRef

  /**
   * The highlight color.
   */
  color: string

  /**
   * Client-side creation time
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A color highlight on exactly one verse. Clients use a canonical verse-derived record key, so a repository has one highlight per verse. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    verse: /*#__PURE__*/ l.ref<ApostilbibleAnnotation.VerseRef>(
      (() => ApostilbibleAnnotation.verseRef) as any,
    ),
    color: /*#__PURE__*/ l.string(),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
