/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth-client-metadata[.]json'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as TranslationBookChapterRouteImport } from './routes/$translation.$book.$chapter'
import { Route as ApiTapWebhookRouteImport } from './routes/api/tap/webhook'
import { Route as BookChapterRouteTmpRouteImport } from './routes/book-chapter.route.tmp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth-client-metadata.json',
    path: '/oauth-client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslationBookChapterRoute = TranslationBookChapterRouteImport.update({
  id: '/$translation/$book/$chapter',
  path: '/$translation/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapWebhookRoute = ApiTapWebhookRouteImport.update({
  id: '/api/tap/webhook',
  path: '/api/tap/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const BookChapterRouteTmpRoute = BookChapterRouteTmpRouteImport.update({
  id: '/book-chapter/route/tmp',
  path: '/book-chapter/route/tmp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/book-chapter/route/tmp': typeof BookChapterRouteTmpRoute
  '/$translation/$book/$chapter': typeof TranslationBookChapterRoute
  '/api/tap/webhook': typeof ApiTapWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/book-chapter/route/tmp': typeof BookChapterRouteTmpRoute
  '/$translation/$book/$chapter': typeof TranslationBookChapterRoute
  '/api/tap/webhook': typeof ApiTapWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/book-chapter/route/tmp': typeof BookChapterRouteTmpRoute
  '/$translation/$book/$chapter': typeof TranslationBookChapterRoute
  '/api/tap/webhook': typeof ApiTapWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oauth-client-metadata.json'
    | '/oauth/callback'
    | '/book-chapter/route/tmp'
    | '/$translation/$book/$chapter'
    | '/api/tap/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth-client-metadata.json'
    | '/oauth/callback'
    | '/book-chapter/route/tmp'
    | '/$translation/$book/$chapter'
    | '/api/tap/webhook'
  id:
    | '__root__'
    | '/'
    | '/oauth-client-metadata.json'
    | '/oauth/callback'
    | '/book-chapter/route/tmp'
    | '/$translation/$book/$chapter'
    | '/api/tap/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  BookChapterRouteTmpRoute: typeof BookChapterRouteTmpRoute
  TranslationBookChapterRoute: typeof TranslationBookChapterRoute
  ApiTapWebhookRoute: typeof ApiTapWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-client-metadata.json': {
      id: '/oauth-client-metadata.json'
      path: '/oauth-client-metadata.json'
      fullPath: '/oauth-client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$translation/$book/$chapter': {
      id: '/$translation/$book/$chapter'
      path: '/$translation/$book/$chapter'
      fullPath: '/$translation/$book/$chapter'
      preLoaderRoute: typeof TranslationBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tap/webhook': {
      id: '/api/tap/webhook'
      path: '/api/tap/webhook'
      fullPath: '/api/tap/webhook'
      preLoaderRoute: typeof ApiTapWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-chapter/route/tmp': {
      id: '/book-chapter/route/tmp'
      path: '/book-chapter/route/tmp'
      fullPath: '/book-chapter/route/tmp'
      preLoaderRoute: typeof BookChapterRouteTmpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  BookChapterRouteTmpRoute: BookChapterRouteTmpRoute,
  TranslationBookChapterRoute: TranslationBookChapterRoute,
  ApiTapWebhookRoute: ApiTapWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
